version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

    groups:
      # group minor & patch updates to reduce noise
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    allow:
      - dependency-type: "direct"
