version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

    groups:
      # React (majors only)
      react-related:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "major"

      # Linting (majors only)
      linting:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
        update-types:
          - "major"

      # Vite (majors only)
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
        update-types:
          - "major"

      # Fortawesome (majors only)
      fontawesome:
        patterns:
          - "@fortawesome/*"
        update-types:
          - "major"

      # group minor & patch updates to reduce noise
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

    allow:
      - dependency-type: "direct"
